### ISSUE TITLE
Cannot find module './star-ratings'

### ISSUE THREAD

**Issue by Argonautic** [ekeric13/react-star-ratings#1]
It looks like that the module index.js in the build folder is improperly pathed when trying to pull from the star-ratings.js file in the src folder, which is causing an error when react-star-ratings is imported. Simply modifying the two './' imports in build/index.js also causes the program to crash as well

**Comment by obedparla** [comment]
+1 to this issue.

**Comment by obedparla** [comment]
I'm getting: Module not found: Error: Can't resolve './star-ratings' in '/Users/obepar/Documents/projects/livecasino-react/node_modules/react-star-ratings/build'

**Comment by fbownz** [comment]
Any update on this issue?

**Comment by anvk** [comment]
Same issue.

**Comment by joemillervi** [comment]
This was the best lookin' one i could find though so i copy pasted index.js and the src dir into my project :1st_place_medal:

**Comment by ekeric13** [comment]
Wow. Just saw this sorry.

Fixed the issue. Also updated it to work with react 16.
