### ISSUE TITLE
disable rating?

### ISSUE THREAD

**Issue by chirastefan** [ekeric13/react-star-ratings#17]
Is there a way to disable the rating, just for the view? I noticed that there was a flag (isSelectable) in the previous version of the API, but that's not the case for the API v2. Is there another way of disabling this and why is this feature removed anyway? it's kind of helpful.

**Comment by chirastefan** [comment]
nevermind.....removing the "changeRating" prop does just that.

**Comment by uchikuch** [comment]
Or you could parse `null` to the "changeRating" prop.
