### ISSUE TITLE
Firefox display stare very big

### ISSUE THREAD

**Issue by hemedani** [ekeric13/react-star-ratings#2]
the star viewed in chrome very well :
![capto_capture 1396-09-09_08-38-16_](https://user-images.githubusercontent.com/6236123/33415318-f7e5601c-d5aa-11e7-939a-6786ef5fbbdb.png)

but in `firefox 57.0.1 ` displayed very big :
![screenshot-2017-11-30 pinteb](https://user-images.githubusercontent.com/6236123/33415342-24e4ef1a-d5ab-11e7-8ab8-9c43ee63ca88.png)

**Comment by hemedani** [comment]
I'm forget to set unit for `starWidthAndHeight` and `starSpacing` and after sees your codepen and set the unit fixed in firefox too :
```javascript

                    <StarRatings
                      rating={this.rateCalc('quality')}
                      starWidthAndHeight='20'
                      starSpacing='4'
                      isAggregateRating={false}
                      numOfStars={ 5 }
                    />
```
chaned to :
```javascript

                    <StarRatings
                      rating={this.rateCalc('quality')}
                      starWidthAndHeight={'20px'}
                      starSpacing={'4px'}
                      isAggregateRating={false}
                      numOfStars={ 5 }
                    />
```

**Comment by ekeric13** [comment]
@hemedani Did that change fix it? I am not seeing any issues in firefox...
<img width="735" alt="screen shot 2017-12-07 at 2 14 15 pm" src="https://user-images.githubusercontent.com/6489651/33741383-edeb9c3a-db58-11e7-8d6b-ac2b6d317327.png">

**Comment by hemedani** [comment]
yes when setting unit everything working fine.
please set a `px` for a default unit and when we forget to set that automatically fixing  unit for us
tank you
