### ISSUE TITLE
Tooltip issue

### ISSUE THREAD

**Issue by ahadortiz** [ekeric13/react-star-ratings#3]
The star tooltip become '4. Stars' for 4.9 rating.
I looked at the source code and found the reason.
![image](https://user-images.githubusercontent.com/31257875/33739314-8b0cd9d8-dbd7-11e7-986c-b78008e4eafd.png)
Please see the attached screenshot.
I guess you wanted to remove 0 at end, but you didn't count dot (.)
formattedRating = formattedRating.slice(0, 2);
so 4.90 will be 4.

**Comment by ekeric13** [comment]
Nice catch! 

I think I fixed it here:
https://github.com/ekeric13/react-star-ratings/commit/3ad0c242f4f344fe5cf87bc1740f3473d9089cac

Let me know if the issue still persists.
