### ISSUE TITLE
IE not support fill() method.

### ISSUE THREAD

**Issue by luizrrodrigues** [ekeric13/react-star-ratings#5]
In docs say that supports IE9+, but IE not support fill() method.

![10232cb75bbb502d2838554a7f5f7542](https://user-images.githubusercontent.com/7029641/35884429-cac54910-0b71-11e8-8aae-70f5dec24786.png)

![ce4eff54514ed3779d9e82cd47ded842](https://user-images.githubusercontent.com/7029641/35884459-e1504270-0b71-11e8-9794-b08cb0fd22ba.png)

**Comment by ekeric13** [comment]
Oh shoot. I thought babel would have compiled that to a format that supports ie. I can make a change so that I don't use fill though, so no worries.

You can also checkout this repo I made recently as I am pretty sure I don't use fill:

https://github.com/ekeric13/react-ratings-declarative

**Comment by luizrrodrigues** [comment]
Cool, I'll take a look. :) 👍

**Comment by ekeric13** [comment]
@luizrrodrigues Think I got it working without `.fill` for this repo as well now. but for version 2.x. I will need to look into how to release multiple different versions of an npm package before updating the v1 api.

edit: let me know if you experience any issues. I would have to download a vm to test myself on ie. Just did a quick fix that should support ie.

**Comment by luizrrodrigues** [comment]
Just update to latest version, have error with other method **isInteger**.

![2e48c7c11565d3fa092f9f3d3e5e0d3a](https://user-images.githubusercontent.com/7029641/35886320-ce086304-0b77-11e8-9f38-a14b9f13dfd4.png)

**Comment by ekeric13** [comment]
Yeah, looks like that is also not supported.

Let me add the polyfill:

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/isInteger

**Comment by luizrrodrigues** [comment]
humm. Looks like not working well, stars now ignoring 'starWidthAndHeight'

![1aae938aa1d6c1f732f92339107e7ddf](https://user-images.githubusercontent.com/7029641/35887078-4174326c-0b7a-11e8-8850-c95d23cfa3bc.png)

**Comment by ekeric13** [comment]
You might need to change the props if you are using the new api.

https://github.com/ekeric13/react-star-ratings#api-v2

**Comment by luizrrodrigues** [comment]
Wow.. Sorry, my fault.. Looks like all good now.. Thanks for fast replies. :)
