### ISSUE TITLE
changeRating not working

### ISSUE THREAD

**Issue by borisyordanov** [ekeric13/react-star-ratings#6]
I pretty much took the example provided in the package and put it in one of my components. The `changeRating` prop is not executed when i click on any of the stars.

I'm using React 16.2 and react-star-ratings 2.2.0

Here is my changeRating method:
```
changeRating(newRating) {
    this.setState({
        rating: newRating
    });
}
```

And here is how i render the component:
```
<StarRatings
    rating={this.state.rating}
    starRatedColor="blue"
    changeRating={this.changeRating}
    numberOfStars={6}
/>
```

If i edit the state myself the stars get updated and otherwise the component works as expected. The issue is that `this.changeRating` never gets called.

Help!

**Comment by borisyordanov** [comment]
It turns out you need to set the `isSelectable={true}` on the `StarRatings` component to enable selection.

**Comment by ekeric13** [comment]
Are you sure you are on the latest version? it is really weird that `isSelectable` would work since that prop isn't even in the code for version 2.2

https://github.com/ekeric13/react-star-ratings/blob/master/src/star-ratings.js#L178

**Comment by borisyordanov** [comment]
Hi Erik,
I just double checked - i'm using 2.2

I removed `isSelectable` from the component and the change stopped working.

But you're right - it is weird. I deleted the `react-star-ratings` folder from `node_modules` and reinstalled it and it started working without `isSelectable`.

You've made a great library. Thank you!
